version: "3.9"

services:
  backend:
    build:
      context: ./service
    container_name: churn-backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
  frontend:
    build:
      context: ./app
    container_name: churn-frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
